/**
 * @file      hardware.h (180.ARM_Peripherals/Sources/hardware.h)
 *
 * Main header file for USBDM library.
 * Generated code is included via this file.
 *
 * @version  V4.12.1.270
 * @date     1 December 2021
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "error.h"
#include "pin_mapping.h"
#include "delay.h"
#include "console.h"

#include "gpio.h"
#include "pit.h"
#include "adc.h"


namespace USBDM {

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
extern void mapAllPins();

/// General use ADC
typedef Adc0                                                 UserAdc;                                      

/// Analogue input level controlling detection level
typedef Adc0::Channel<4>                                     LevelControl;                                 // PTC2(p35)

/// Analogue input measuring instantaneous load current
typedef Adc0::Channel<5>                                     CurrentSample;                                // PTD1(p42)

/// Analogue input level controlling hold time
typedef Adc0::Channel<13>                                    HoldControl;                                  // PTB3(p30)

/// Analogue input level controlling delay time
typedef Adc0::Channel<14>                                    DelayControl;                                 // PTC0(p33)

/// LED indicating in hold state
typedef GpioTable_T<GpioBInfo, 16, ActiveHigh>               HoldLed;                                      // PTB16(p31)

/// Control for dust collector
typedef GpioTable_T<GpioCInfo, 6, ActiveHigh>                DustCollector;                                // PTC6(p39)

/// LED indicating in delay state
typedef GpioTable_T<GpioCInfo, 1, ActiveHigh>                DelayLed;                                     // PTC1(p34)

/// LED indicating load detection
typedef GpioTable_T<GpioCInfo, 3, ActiveHigh>                DetectLed;                                    // PTC3(p36)

/// General Debug pin
typedef GpioTable_T<GpioDInfo, 7, ActiveHigh>                Debug;                                        // PTD7(p48)

/// General Timer
typedef Pit                                                  UserTimer;                                    

/// Timer channel for polling
typedef Pit::Channel<0>                                      PollingTimerChannel;                          // PIT_CH0(Internal)

} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
