/**
 * @file      irq.h (180.ARM_Peripherals/Project_Headers/irq-MKE.h)
 * @brief    Abstraction layer for IRQ interface
 */

#ifndef PROJECT_HEADERS_IRQ_H_
#define PROJECT_HEADERS_IRQ_H_

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include "pin_mapping.h"

// No handler defined for IRQ


namespace USBDM {

// $/IRQ/peripheral_h_definition not found
template <class Info>
class IrqBase_T : public IrqInfo {

protected:
   /** Hardware instance */
   static constexpr HardwarePtr<IRQ_Type> irq = baseAddress;

// No /IRQ/protectedMethods found
public:
// No /IRQ/publicMethods found

};




}; // namespace USBDM

#endif /* PROJECT_HEADERS_IRQ_H_ */
