/**
 * @file      hardware.h (180.ARM_Peripherals/Sources/hardware.h)
 *
 * Main header file for USBDM library.
 * Generated code is included via this file.
 *
 * @version  V4.12.1.270
 * @date     1 December 2021
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "error.h"
#include "pin_mapping.h"
#include "delay.h"
#include "console.h"

#include "gpio.h"
#include "pit.h"
#include "adc.h"


namespace USBDM {

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
extern void mapAllPins();

/// ADC, Analogue Input
typedef Adc0                                                 UserAdc;                                      

typedef Adc0::Channel<1>                                     Reference;                                    // PTA1(15)

typedef Adc0::Channel<4>                                     I_Sample2;                                    // PTB0(12)

typedef Adc0::Channel<5>                                     I_Sample;                                     // PTB1(11)

typedef Adc0::Channel<6>                                     HoldControl;                                  // PTB2(10)

typedef Adc0::Channel<7>                                     LevelControl;                                 // PTB3(9)

typedef GpioB<4,ActiveHigh>                                  Debug;                                        // PTB4(8)

typedef GpioB<5,ActiveHigh>                                  DustCollector;                                // PTB5(7)

typedef GpioB<7,ActiveHigh>                                  DelayLed;                                     // PTB7(5)

typedef GpioB<6,ActiveHigh>                                  HoldLed;                                      // PTB6(6)

typedef GpioA<2,ActiveHigh>                                  DetectLed;                                    // PTA2(14)

/// PIT, Programmable Interrupt Timer
typedef Pit                                                  UserTimer;                                    

typedef Pit::Channel<0>                                      PollingTimerChannel;                          // PIT_CH0(Internal)

} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
